### ISSUE TITLE
User Story 9 - Dispatcher update trip/load information

### ISSUE THREAD

**Issue by robertneszt** [robertneszt/Truck-Management-System#10]
As a Dispatcher User, I want to update the load information, including price, weight, and size, to manage the transportation process.

**Comment by robertneszt** [comment]
works

**Comment by robertneszt** [comment]
new build broke this feature.
Fix 9 NEEDED: edit function broke, related to STORY 7, 10 issues.

**Comment by weiguangy22** [comment]
Fixed.
