### ISSUE TITLE
User Story 19 - Driver accept or refuse loads

### ISSUE THREAD

**Issue by robertneszt** [robertneszt/Truck-Management-System#21]
As a Driver User, I want to accept or refuse loads based on my availability and capacity, so I can plan my schedule effectively.

**Comment by weiguangy22** [comment]
-Added more trip status: PickedUp and Delivered
- Driver can Reject assigned Trip, but won't be an option if he already picked it up or other status

**Comment by weiguangy22** [comment]
Will work on accept trip
