### ISSUE TITLE
User Story 20 - Driver preview salary re: completed trips

### ISSUE THREAD

**Issue by robertneszt** [robertneszt/Truck-Management-System#22]
As a Driver User, I want to preview my salary based on my rate and the distance traveled in the last week or month, so I can estimate my earnings.

**Comment by weiguangy22** [comment]
This is partially done: driver pay advise page

**Comment by robertneszt** [comment]
Userstory 20:able to show pay rate and total trips, still need to have a calculation for distance between points for trips
