### ISSUE TITLE
User Story 22 - Dispatcher/Driver Maps API in trip/load details

### ISSUE THREAD

**Issue by robertneszt** [robertneszt/Truck-Management-System#25]
As a User (Dispatcher/Driver) viewing load/trip details, I want to see travel routes provided by Google Maps API to optimize trip routing

**Comment by weiguangy22** [comment]
I will work on this one as well: driver side trip detail>> add map api

**Comment by weiguangy22** [comment]
Driver side map api implementation  done with map and direction display
