### ISSUE TITLE
User Story 7 - Dispatcher create trip/load information

### ISSUE THREAD

**Issue by robertneszt** [robertneszt/Truck-Management-System#8]
As a Dispatcher User, I want to create the load information, including price, weight, and size, to manage the transportation process.

**Comment by robertneszt** [comment]
just need trip-driver association

**Comment by robertneszt** [comment]
just need trip-driver association

**Comment by robertneszt** [comment]
FIX 7 NEEDED: no longer functions on latest build, cannot save or edit loads/trips.
Must investigate data mismatch and fix. Related to stories 9, 10

**Comment by weiguangy22** [comment]
Added available driver selector, works now.
